name: cave_ace
description: Cave Ace game

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame_splash_screen: 0.0.1
  flame: ^0.19.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/hector.png
    - assets/images/hector_no_mount.png
    - assets/images/rock_bullet.png
    - assets/images/enemy_rock_bullet.png
    - assets/images/bomb_ptero.png
    - assets/images/shooting_ptero.png
    - assets/images/explosion.png
    - assets/images/ham.png
    - assets/images/box.png

    - assets/images/shield.png

    - assets/images/trunk_gun.png
    - assets/images/trunk_pickup.png

    - assets/images/backgrounds/florest_1.png
    - assets/images/backgrounds/florest_2.png

    - assets/images/title_screen.png
    - assets/images/cptblackpixel.png

    - assets/stages/test.json

  fonts:
   - family: CubeCavern
     fonts:
       - asset: assets/fonts/cubecavern_memesbruh03.ttf
